#!/bin/sh

# Package
PACKAGE="btsync"
DNAME="BitTorrent Sync"

# Others
INSTALL_DIR="/usr/local/${PACKAGE}"
PATH="${INSTALL_DIR}/bin:${PATH}"
USER="user1 user2"
BTSYNC="${INSTALL_DIR}/bin/btsync"
CFG_FILE="${INSTALL_DIR}/var/sync.conf"
PID_FILE="${INSTALL_DIR}/var/syncapp.pid"


start_daemon ()
{
	for BTUSER in $USER; do
		echo "Starting BTsync for ${BTUSER}"
    		su - ${BTUSER} -c "PATH=${PATH} ${BTSYNC} --config /volume1/btsync/${BTUSER}.btsync.conf"
    	done
}

stop_daemon ()
{
	for BTUSER in $USER; do
		USER_PID_FILE="${INSTALL_DIR}/var/syncapp-${BTUSER}.pid"
    		kill `cat ${USER_PID_FILE}`
    		wait_for_status 1 20 "${BTUSER}" || kill -9 `cat ${USER_PID_FILE}`
		rm -f ${USER_PID_FILE}
	done
}

daemon_status ()
{
	if [ -z $1 ]; then
		for BTUSER in $USER; do
			USER_PID_FILE="${INSTALL_DIR}/var/syncapp-${BTUSER}.pid"
			break
		done
	else
		USER_PID_FILE="${INSTALL_DIR}/var/syncapp-$1.pid"
	fi
    	if [ -f ${USER_PID_FILE} ] && kill -0 `cat ${USER_PID_FILE}` > /dev/null 2>&1; then
        	return
    	fi
    	rm -f ${USER_PID_FILE}
    	return 1
}

wait_for_status ()
{
    counter=$2
    while [ ${counter} -gt 0 ]; do
        daemon_status $3
        [ $? -eq $1 ] && return
        let counter=counter-1
        sleep 1
    done
    return 1
}


case $1 in
    start)
        if daemon_status; then
            echo ${DNAME} is already running
        else
            echo Starting ${DNAME} ...
            start_daemon
        fi
        ;;
    stop)
        if daemon_status; then
            echo Stopping ${DNAME} ...
            stop_daemon
        else
            echo ${DNAME} is not running
        fi
        ;;
    status)
        if daemon_status; then
            echo ${DNAME} is running
            exit 0
        else
            echo ${DNAME} is not running
            exit 1
        fi
        ;;
    log)
        exit 1
        ;;
    *)
        exit 1
        ;;
esac
